services:
  webhook:
    build: .
    restart: unless-stopped
    volumes:
      - ./hooks:/etc/webhook
      - ./scripts:/scripts
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook.rule=Host(`${WEBHOOK_DOMAIN}`)
      - traefik.http.routers.webhook.entrypoints=websecure
      - traefik.http.routers.webhook.tls.certresolver=letsencrypt
      - traefik.http.services.webhook.loadbalancer.server.port=9000
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
